name: dtorrent_task_v2
description: BitTorrent download client package written by pure Dart language.
version: 0.4.5
repository: https://github.com/atlet99/dtorrent_task_v2
issue_tracker: https://github.com/atlet99/dtorrent_task_v2/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dtorrent_parser: ^1.0.8
  dtorrent_tracker: ^1.3.18
  bittorrent_dht: ^0.0.12
  dtorrent_common: ^1.0.7
  b_encode_decode: ^1.0.4
  utp_protocol: ^1.0.4
  dart_ipify: ^1.1.1
  events_emitter2: ^1.0.3
  mime: ^2.0.0
  collection: ^1.19.0
  crypto: ^3.0.6
  args: ^2.7.0
  logging: ^1.2.0
  http: ^1.6.0

dev_dependencies:
  lints: ^6.0.0
  path: ^1.9.0
  test: ^1.24.8
